// <auto-generated/>
namespace Game.Code.GameLayers.Category
{
	using System;
	[Flags]
	public enum CategoryId
	{
		Hero = 1 << 1,
		MainBuilding = 1 << 2,
		Creep = 1 << 3,
		Boss = 1 << 4,
		SiegeCreep = 1 << 5,
		AssassinCreep = 1 << 6,
	}
}
